# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e2c812bdcb24721fac29beaed2e0de731090dcf86d5b7ad2a1560c9b6fb36d023d3eb03072a27774861c150f92cc6333bf5afc802c1a93c527679d7b0a20208

test:
  secret_key_base: 586426890f4aab5be744c166424b237e5529e61c194b7acea7535650248585a33b386e8252bc53918d7c05e49839ef06a195604f8e5abdd97d4a2e310e2c95ea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
